#!/usr/bin/env python3
# PlatformIO library pre-build hook (wired via library.json -> build.extraScript).
# Ensures matter_c's gated attestation header exists before the library compiles.
#
# include/mtrc_attest_creds.h is gitignored + GENERATED by test/gen_csa_creds.py
# (the CSA test DAC/PAI/CD set, VID 0xFFF1/PID 0x8000). After a `git clean` or a
# fresh upstream merge the untracked file is gone, and matter_c.c fails with
# "mtrc_attest_creds.h: No such file or directory" (the include is gated behind
# -DMTRC_ATTEST_TEST_CREDS, which the Matter envs set). Regenerating it by hand
# was a footgun; this makes the build self-healing.
#
# Only fires when the header is missing (a no-op on every normal build), and only
# runs at all when matter_c is part of the build (this script belongs to the lib).
import os
import subprocess
import sys

Import("env")  # noqa: F821  (injected by PlatformIO)

mc_dir = os.path.join(env.subst("$PROJECT_DIR"), "lib", "libesp32_div", "matter_c")  # noqa: F821
header = os.path.join(mc_dir, "include", "mtrc_attest_creds.h")

if not os.path.isfile(header):
    gen = os.path.join(mc_dir, "test", "gen_csa_creds.py")
    print("matter_c: mtrc_attest_creds.h missing -> generating via gen_csa_creds.py")
    try:
        subprocess.run([sys.executable, gen], check=True)
    except Exception as e:  # don't hard-crash the whole build from the hook
        print("matter_c: WARNING could not generate attestation header: %s" % e,
              file=sys.stderr)
