// test_cert.c — Matter operational certificate (TLV) parser test.
// Parses a NOC + RCAC generated by chip-equivalent Python and checks the
// extracted fields. Build/run host-side: see test/build_cert.sh.

#include <stdio.h>
#include <string.h>
#include "mtrc_cert.h"

static int g_ok = 1;
static void chk(const char *l, int c){ printf("  [%s] %s\n", c?"PASS":"FAIL", l); g_ok &= c; }
static int hex2bin(const char *h, uint8_t *o, size_t m){ size_t n=strlen(h)/2; if(n>m)return -1;
  for(size_t i=0;i<n;i++){unsigned v;sscanf(h+2*i,"%2x",&v);o[i]=(uint8_t)v;} return (int)n; }

static const char *NOC =
 "1530010801020304050607082402013703271401000000cacacaca182604000000292605000000353706271501000000b0fa0000271188776655443322111824070124080130094104000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f370a35012801182502010018300b40404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f18";
static const char *RCAC =
 "1530010209092402013703271401000000cacacaca182604000000292605000000353706271401000000cacacaca1824070124080130094104404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f370a35012901182502600018300b40808182838485868788898a8b8c8d8e8f909192939495969798999a9b9c9d9e9fa0a1a2a3a4a5a6a7a8a9aaabacadaeafb0b1b2b3b4b5b6b7b8b9babbbcbdbebf18";

int main(void) {
  printf("matter_c operational-certificate parser test\n");
  uint8_t buf[512]; mtrc_cert c;

  printf("(A) NOC\n");
  int n = hex2bin(NOC, buf, sizeof(buf));
  chk("parse ok", n>0 && mtrc_cert_parse(buf, (size_t)n, &c));
  chk("subject node-id",   c.have_node_id   && c.subject_node_id   == 0x1122334455667788ULL);
  chk("subject fabric-id", c.have_fabric_id && c.subject_fabric_id == 0x0000FAB000000001ULL);
  chk("issuer rcac-id",    c.issuer_has_rcac&& c.issuer_rcac_id    == 0xCACACACA00000001ULL);
  chk("is-CA false",       c.is_ca == false);
  chk("pubkey 04|00..3f",  c.have_pubkey && c.pubkey[0]==0x04 && c.pubkey[1]==0x00 && c.pubkey[64]==0x3f);
  chk("signature present", c.have_sig && c.signature[0]==0x40 && c.signature[63]==0x7f);

  printf("(B) RCAC\n");
  n = hex2bin(RCAC, buf, sizeof(buf));
  chk("parse ok", n>0 && mtrc_cert_parse(buf, (size_t)n, &c));
  chk("subject rcac-id",   c.have_rcac_id && c.subject_rcac_id == 0xCACACACA00000001ULL);
  chk("is-CA true",        c.is_ca == true);
  chk("no node-id",        !c.have_node_id);
  chk("pubkey 04|40..",    c.have_pubkey && c.pubkey[0]==0x04 && c.pubkey[1]==0x40);

  printf("(C) structural chain check (partial A1b)\n");
  mtrc_cert noc_c, rcac_c; uint8_t buf2[512];
  int nn = hex2bin(NOC,  buf,  sizeof(buf));  mtrc_cert_parse(buf,  (size_t)nn, &noc_c);
  int mm = hex2bin(RCAC, buf2, sizeof(buf2)); mtrc_cert_parse(buf2, (size_t)mm, &rcac_c);

  chk("NOC ok on its fabric (no ICAC)",
      mtrc_cert_chain_check(&noc_c, NULL, 0x0000FAB000000001ULL, 0) == 1);
  chk("NOC rejected on wrong fabric",
      mtrc_cert_chain_check(&noc_c, NULL, 0xDEADBEEFDEADBEEFULL, 0) == 0);
  chk("NOC ok when fabric unknown (0)",
      mtrc_cert_chain_check(&noc_c, NULL, 0, 0) == 1);
  chk("CA cert rejected as NOC",
      mtrc_cert_chain_check(&rcac_c, NULL, 0x0000FAB000000001ULL, 0) == 0);
  chk("NULL NOC rejected",
      mtrc_cert_chain_check(NULL, NULL, 0, 0) == 0);

  // validity window (synthetic: stamp a copy with a known [100,200] window)
  mtrc_cert vc = noc_c; vc.not_before = 100; vc.not_after = 200;
  chk("validity within window ok",
      mtrc_cert_chain_check(&vc, NULL, 0x0000FAB000000001ULL, 150) == 1);
  chk("validity after not_after rejected",
      mtrc_cert_chain_check(&vc, NULL, 0x0000FAB000000001ULL, 300) == 0);
  chk("validity before not_before rejected",
      mtrc_cert_chain_check(&vc, NULL, 0x0000FAB000000001ULL,  50) == 0);
  chk("validity now=0 skips window",
      mtrc_cert_chain_check(&vc, NULL, 0x0000FAB000000001ULL,   0) == 1);

  printf("\n==> cert parser %s\n", g_ok ? "PASS" : "FAIL");
  return g_ok ? 0 : 1;
}
